Fixed crash when loading amiibo file browser
HiddenRamblings/TagMo pull request #240
Opened 2021-06-23 17:15 UTC by sosaria7

When loading amiibo file browser, it crashed with exception on some conditions.

the callstack looks like this:
    java.lang.IllegalArgumentException: Comparison method violates its general contract!
        at java.util.TimSort.mergeLo(TimSort.java:777)
        at java.util.TimSort.mergeAt(TimSort.java:514)
        at java.util.TimSort.mergeCollapse(TimSort.java:439)
        at java.util.TimSort.sort(TimSort.java:245)
        at java.util.Arrays.sort(Arrays.java:1492)
        at java.util.ArrayList.sort(ArrayList.java:1470)
        at java.util.Collections.sort(Collections.java:206)
        at com.hiddenramblings.tagmo.BrowserAmiibosAdapter$AmiiboFilter.publishResults(BrowserAmiibosAdapter.java:330)
        at android.widget.Filter$ResultsHandler.handleMessage(Filter.java:284)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7860)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)

2021-06-23 17:35 UTC, burndive commented
This looks good to me.  Who needs to approve this to get it merged?

2021-08-07 09:14 UTC, AbandonedCart commented
@burndive Take a look at the repository. The last commit to be merged was April 2, 2020.

2021-08-07 09:16 UTC, AbandonedCart requested changes
Are you not the original author of this code or can it be squashed into a single commit?

2021-09-11 03:36 UTC, AbandonedCart commented
Merged to https://github.com/HiddenRamblings/TagMo/tree/experimental release

2021-09-11 03:36 UTC, closed without merging